### ISSUE TITLE
HMR throwing error on file save

### ISSUE THREAD

**Issue by ShiftyMcCool** [gdi2290/angular-starter#2020]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @TipeIO](https://twitter.com/TipeIO)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
starting the server with "npm run start:hmr" starts the server and runs the page without issue.  However, when a file is changed the console shows the below output and fully reloads the page.

```
[WDS] App updated. Recompiling...
VM21 localhost:3000:133 [WDS] 0% - compiling.
VM21 localhost:3000:133 [WDS] 10% - building modules (0/1 modules).
VM21 localhost:3000:133 [WDS] 10% - building modules (0/2 modules).
VM21 localhost:3000:133 [WDS] 10% - building modules (1/2 modules).
VM21 localhost:3000:133 [WDS] 10% - building modules (2/2 modules).
VM21 localhost:3000:133 [WDS] 10% - building modules (2/3 modules).
VM21 localhost:3000:133 [WDS] 10% - building modules (3/3 modules).
VM21 localhost:3000:133 [WDS] 71% - sealing.
VM21 localhost:3000:133 [WDS] 72% - optimizing.
VM21 localhost:3000:133 [WDS] 73% - basic module optimization.
VM21 localhost:3000:133 [WDS] 74% - module optimization.
VM21 localhost:3000:133 [WDS] 75% - advanced module optimization.
VM21 localhost:3000:133 [WDS] 76% - basic chunk optimization.
VM21 localhost:3000:133 [WDS] 76% - basic chunk optimization (pass 2).
VM21 localhost:3000:133 [WDS] 76% - basic chunk optimization (pass 3).
VM21 localhost:3000:133 [WDS] 76% - basic chunk optimization (pass 4).
VM21 localhost:3000:133 [WDS] 77% - chunk optimization.
VM21 localhost:3000:133 [WDS] 78% - advanced chunk optimization.
VM21 localhost:3000:133 [WDS] 79% - module and chunk tree optimization.
VM21 localhost:3000:133 [WDS] 80% - chunk modules optimization.
VM21 localhost:3000:133 [WDS] 81% - advanced chunk modules optimization.
VM21 localhost:3000:133 [WDS] 82% - module reviving.
VM21 localhost:3000:133 [WDS] 83% - module order optimization.
VM21 localhost:3000:133 [WDS] 84% - module id optimization.
VM21 localhost:3000:133 [WDS] 85% - chunk reviving.
VM21 localhost:3000:133 [WDS] 86% - chunk order optimization.
VM21 localhost:3000:133 [WDS] 87% - chunk id optimization.
VM21 localhost:3000:133 [WDS] 88% - hashing.
VM21 localhost:3000:133 [WDS] 89% - module assets processing.
VM21 localhost:3000:133 [WDS] 90% - chunk assets processing.
VM21 localhost:3000:133 [WDS] 91% - additional chunk assets processing.
VM21 localhost:3000:133 [WDS] 92% - recording.
VM21 localhost:3000:133 [WDS] 91% - additional asset processing.
VM21 localhost:3000:133 [WDS] 92% - chunk asset optimization.
VM21 localhost:3000:133 [WDS] 94% - asset optimization.
VM21 localhost:3000:133 [WDS] 95% - emitting.
VM21 localhost:3000:133 [WDS] 100% - Compilation completed.
VM21 localhost:3000:223 [WDS] App hot update...
VM46 log.js:23 [HMR] Checking for updates on the server...
VM46 log.js:25 [HMR] Cannot apply update. Need to do a full reload!
module.exports @ VM46 log.js:25
(anonymous) @ VM45 dev-server.js:34
ZoneDelegate.invoke @ VM149 zone.js:388
Zone.run @ VM149 zone.js:138
(anonymous) @ VM149 zone.js:872
ZoneDelegate.invokeTask @ VM149 zone.js:421
Zone.runTask @ VM149 zone.js:188
drainMicroTaskQueue @ VM149 zone.js:595
Promise.then (async)
scheduleMicroTask @ VM149 zone.js:578
ZoneDelegate.scheduleTask @ VM149 zone.js:410
Zone.scheduleTask @ VM149 zone.js:232
Zone.scheduleMicroTask @ VM149 zone.js:252
scheduleResolveOrReject @ VM149 zone.js:862
ZoneAwarePromise.then @ VM149 zone.js:962
hotUpdateDownloaded @ VM19 inline.bundle.js:318
hotAddUpdateChunk @ VM19 inline.bundle.js:295
webpackHotUpdateCallback @ VM19 inline.bundle.js:37
(anonymous) @ VM375 5.eb7e84554c548ebbf21c.hot-update.js:1
VM46 log.js:25 [HMR] Error: Aborted because ./src/app/home/home.component.html is not accepted
Update propagation: ./src/app/home/home.component.html -> ./src/app/home/home.component.ts -> ./src/app/home/index.ts -> ./src/app/app.module.ts -> ./src/app/index.ts -> ./src/main.browser.ts -> 1
    at hotApply (http://localhost:3000/inline.bundle.js:470:30)
    at http://localhost:3000/inline.bundle.js:319:21
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388:26)
    at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:138:43)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:872:34)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:595:35)
module.exports @ VM46 log.js:25
(anonymous) @ VM45 dev-server.js:35
ZoneDelegate.invoke @ VM149 zone.js:388
Zone.run @ VM149 zone.js:138
(anonymous) @ VM149 zone.js:872
ZoneDelegate.invokeTask @ VM149 zone.js:421
Zone.runTask @ VM149 zone.js:188
drainMicroTaskQueue @ VM149 zone.js:595
Promise.then (async)
scheduleMicroTask @ VM149 zone.js:578
ZoneDelegate.scheduleTask @ VM149 zone.js:410
Zone.scheduleTask @ VM149 zone.js:232
Zone.scheduleMicroTask @ VM149 zone.js:252
scheduleResolveOrReject @ VM149 zone.js:862
ZoneAwarePromise.then @ VM149 zone.js:962
hotUpdateDownloaded @ VM19 inline.bundle.js:318
hotAddUpdateChunk @ VM19 inline.bundle.js:295
webpackHotUpdateCallback @ VM19 inline.bundle.js:37
(anonymous) @ VM375 5.eb7e84554c548ebbf21c.hot-update.js:1
Navigated to http://localhost:3000/
log.js:23 [HMR] Waiting for update signal from WDS...
client:77 [WDS] Hot Module Replacement enabled.
dev-module.module.ts:22 `DevModuleModule` module initialized
app.component.ts:74 Initial App State {}
core.js:3688 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
home.component.ts:46 hello `Home` component
barrel.component.ts:11 `Barrel` component loaded asynchronously
barrel.module.ts:9 `Barrel` bundle loaded asynchronously
detail.component.ts:11 `Detail` component loaded asynchronously
detail.module.ts:9 `Detail` bundle loaded asynchronously
child-barrel.component.ts:11 `ChildBarrel` component loaded asynchronously
child-barrel.module.ts:9 `ChildBarrel` bundle loaded asynchronously
child-detail.component.ts:11 `ChildDetail` component loaded asynchronously
child-detail.module.ts:9 `ChildDetail` bundle loaded asynchronously
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Nothing special was done.  Downloaded the code as a zip and followed the install process.  The above scenario happens anytime a file is saved

* **What is the expected behavior?**
Module is reloaded while preserving state

* **What is the motivation / use case for changing the behavior?**
I would like to use this as a skeleton for a new app

* **Please tell us about your environment:**

- Angular version: 4.x.x
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Windows 10
Chrome 67.0.3396.99

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I found a solution that adds:
```
if (module.hot)
module.hot.accept()
```
to the entry point.  I took a guess and added to main.browser.ts.  This makes the error go away but state is not preserved.  The page seems not to fully reload either but since state is not preserved I'm not sure that's the case.
For full disclosure, due to my company firewall the postinstall script fails (npm run webdriver:update).  Let me know if this could be the issue.

**Comment by lanovoy** [comment]
Should be now fixed in the master branch.

**Comment by ShiftyMcCool** [comment]
Hello @lanovoy .

Thanks for the quick response, but all is not fixed.  After re-cloning the repo and setting everything up I'm still getting similar behavior.  I don't get the error but the page still loses state during "hot reloads".  It's the same result as adding 
```
if (module.hot)
module.hot.accept()
```
to the entry point.

Any suggestions?
